### ISSUE TITLE
Compass does not stop spinning upon game start and cannot be stopped.

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#69] opened 2022-08-06 21:53 UTC
When starting a new game, the message box appears - the game adjusts towards north in the background.
After closing this message, the game does not stop spinning and cannot be stopped.

**To Reproduce**
1. start new game.
2. close message box
3. skip tips
4. see the game spnning

**Expected behavior**
the game should stop spinning.

**Screenshots**
no screenshot, cannot be seen on screenshot.

**Desktop (please complete the following information):**
windows 10, latest patch level.
nvidia gpu / latest driver.

**Comment by slashman** [comment] 2022-08-08 02:55
Unable to reproduce this, I wonder if there's some input device connected or similar, causing the spinning.

**Comment by Stoltverd** [comment] 2022-08-08 14:22
Hello!
Does this happen only to the compass or to the world itself?

**Comment by Kaytila** [comment] 2022-08-08 20:04
There only is a mouse and keyboard attached, nothing else.
Wait, there was my PC Joystick (Flightstick something) attached. Removing it, made it stop.
Adding it did not make it appear again.
Hmmmm, not sure this was the issue. What to do with this now?

**Comment by Stoltverd** [comment] 2022-08-08 21:09
I'd imagine it was an issue with one of the axis. Especially if it's one of those joysticks that you can turn.
We have been having issues with our input system. 
We're working on it!
Thank you for the update!

**Comment by Stoltverd** [comment] 2022-08-17 02:49
It will be fixed in the coming weeks by @slashman

**Closed as completed by Stoltverd** 2022-08-17 02:49 UTC
Labels: bug
