### ISSUE TITLE
Map: towns/huts are not labelled

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#43] opened 2021-05-27 08:57 UTC
towns or huts are not labelled
<img width="698" alt="2021-05-27 10_56_16-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119797109-3bc75800-beda-11eb-9d25-0211c6e766fb.png">

**Comment by slashman** [comment] 2021-05-27 11:08
This is half-bug half-intended behavior. I want only the bigger towns be labelled, however it's not being controlled right now. Looks like a restore-game issue.

**Comment by Kaytila** [comment] 2021-05-27 15:58
No, new game with 0.26.2.

**Comment by slashman** [comment] 2021-07-02 19:05
Fixed in v0.28.4

**Closed by slashman** 2021-07-02 19:05 UTC
Labels: bug
